# Generated by Django 6.0.3 on 2026-03-26 08:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id_in', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'ingredients',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Login', models.CharField(max_length=255, unique=True, verbose_name='Логин')),
                ('Password', models.CharField(max_length=255)),
                ('Image', models.CharField(blank=True, max_length=255, null=True, verbose_name='Изображение')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
            },
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('time', models.IntegerField(blank=True, null=True)),
                ('Calories', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('photo', models.CharField(blank=True, max_length=255, null=True)),
                ('ID_user', models.ForeignKey(db_column='ID_user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'receipt',
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('add_time', models.DateTimeField(auto_now_add=True)),
                ('user_id', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('recipe_id', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.receipt')),
            ],
            options={
                'db_table': 'favorites',
            },
        ),
        migrations.CreateModel(
            name='ReceiptCategory',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Cat_Id', models.ForeignKey(db_column='Cat_Id', on_delete=django.db.models.deletion.CASCADE, to='accounts.category')),
                ('Rec_ID', models.ForeignKey(db_column='Rec_ID', on_delete=django.db.models.deletion.CASCADE, to='accounts.receipt')),
            ],
            options={
                'db_table': 'receiptcategory',
            },
        ),
        migrations.CreateModel(
            name='RecipeIngredient',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('unit', models.IntegerField(blank=True, null=True)),
                ('Ingredient_id', models.ForeignKey(db_column='Ingredient_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.ingredient')),
                ('recipe_id', models.ForeignKey(db_column='recipe_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.receipt')),
            ],
            options={
                'db_table': 'recipeingredient',
            },
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
