# Generated by Django 6.0.3 on 2026-03-26 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_category_ingredient_user_receipt_favorite_and_more'),
    ]

    operations = [
    ]
