"""Initial migration

Revision ID: eb23e5ae210c
Revises: 
Create Date: 2026-03-25 09:24:10.956183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb23e5ae210c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('name')
    )
    op.create_table('ingredients',
    sa.Column('id_in', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_in'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Login', sa.String(), nullable=False),
    sa.Column('Password', sa.String(), nullable=False),
    sa.Column('Image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('ID'),
    sa.UniqueConstraint('Login')
    )
    op.create_table('receipt',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('time', sa.Integer(), nullable=True),
    sa.Column('Calories', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ID_user', sa.Integer(), nullable=False),
    sa.Column('photo', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['ID_user'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('favorites',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('add_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recipe_id'], ['receipt.ID'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('receiptcategory',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Rec_ID', sa.Integer(), nullable=False),
    sa.Column('Cat_Id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Cat_Id'], ['category.ID'], ),
    sa.ForeignKeyConstraint(['Rec_ID'], ['receipt.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    op.create_table('recipeingredient',
    sa.Column('ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('recipe_id', sa.Integer(), nullable=False),
    sa.Column('Ingredient_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Ingredient_id'], ['ingredients.id_in'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['receipt.ID'], ),
    sa.PrimaryKeyConstraint('ID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipeingredient')
    op.drop_table('receiptcategory')
    op.drop_table('favorites')
    op.drop_table('receipt')
    op.drop_table('user')
    op.drop_table('ingredients')
    op.drop_table('category')
    # ### end Alembic commands ###
